### ISSUE TITLE
CORS seems OK but now getting CSP error

### ISSUE THREAD

**Issue by enwinn** [honnamkuan/cors-cache-proxy#1]
Just tried this based on your Medium Article: https://medium.com/swlh/setup-a-node-js-cors-proxy-with-caching-support-632e83ea82e6

When I run `await fetch('https://bloomberg.com')` in the browser web developer tool console I get a CORS request blocked.

When I setup your cors-cache-proxy example and then run `await fetch('http://localhost:8080/https://bloomberg.com')` in the console, the CORS error is gone but now there is this error:

`Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:8080/https://bloomberg.com (“connect-src”).`

Also interesting - just running `curl.exe -v https://www.bloomberg.com` displayed a location value with the bloomberg.com URL with a UUID appended that when you paste it into a browser displays content stating they detected suspicious activity and to click and hold your cursor on a page element. That displays a progress bar that upon completion ends up displaying the https://www.bloomberg.com homepage.

Thoughts?

One final note - `npm audit` is not very happy with some of your dependencies...

**Comment by hnkuanx** [comment]
Regarding the vulnerability, this project uses `cors-anywhere`. 
see https://github.com/Rob--W/cors-anywhere/issues/254#issuecomment-659037020
The vulnerable method is not used and hence no vulnerability.


Try to run
```
await fetch('http://localhost:8080/https://www.bloomberg.com')
```
instead of
```
await fetch('http://localhost:8080/https://bloomberg.com')
```

It works well
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/5896391/180597986-1af0ebaa-5e8e-485d-845a-4fc3b9074746.png">

**Comment by enwinn** [comment]
Yes, I had tried different variants. For me, the result is the same. Note the one fetch without using the proxy throws the CORS error and the fetches using the proxy do not but they do throw CSP errors.

Seems to do the same thing no matter what endpoint I try and fetch.  Since it works for you but not me that suggests something different in my environment. I will explore further in different environments.

![image](https://user-images.githubusercontent.com/11488937/180611969-6d257126-9cd6-4304-a14e-6ec11d696371.png)

I used https://cspvalidator.org/#url=https://www.bloomberg.com/  in my browser and got this result which demonstrates what I tried to describe when I tested using curl:

![image](https://user-images.githubusercontent.com/11488937/180616625-2a232869-899b-4d4e-8759-9b87ec439248.png)

If you plug in that `location` header value into the browser address bar you get this:

![image](https://user-images.githubusercontent.com/11488937/180616657-9225f513-1fda-4e04-80ac-cc567a3657eb.png)

Click and hold as directed:

![image](https://user-images.githubusercontent.com/11488937/180616722-168e1628-ffc0-4a81-a2e6-ef15509e0f3e.png)

And you get the expected result:

![image](https://user-images.githubusercontent.com/11488937/180616755-5a71dcb2-297d-442b-9941-628db5ab515c.png)

The headers indicate Bloomberg is using the Varnish CDN: https://www.varnish-software.com/ 

curl result using `.\curl.exe -v https://www.bloomberg.com/`:

![image](https://user-images.githubusercontent.com/11488937/180617190-54e76002-f2e1-4c56-a675-e0054730e9fc.png)

curl result using `.\curl.exe -v http://localhost:8080/https://www.bloomberg.com/`:
Note the location value returned `localhost:5000` instead of `localhost:8080` further indicating your proxy is indeed working but I'm stumped as to why I am getting a CSP error.

![image](https://user-images.githubusercontent.com/11488937/180617359-40a3d831-0bac-4769-bffa-24e7079072e7.png)

Interestingly, if I test using Firefox, the response pops right to the Bloomberg web page without any error indications:

![image](https://user-images.githubusercontent.com/11488937/180617822-e6e0643b-a3b9-4255-aa63-c2cab3d45e78.png)

This also captures that `location` header mechanism Bloomberg has going on:

`https://securityheaders.com/?q=www.bloomberg.com&followRedirects=on`

![image](https://user-images.githubusercontent.com/11488937/180618332-3f6729d5-e5a7-42bc-aa75-44fee747004d.png)


Hmmm, later attempts in the same browser session for Bloomberg using `https://securityheaders.com` work and display an 'A' report card.

**Comment by enwinn** [comment]
Update: on my MBP, running macOS 12.5 on my home network, with Safari v15.6 the use case works as your reply above and your article demonstrates:

![image](https://user-images.githubusercontent.com/11488937/180626649-ed48b8bc-68e8-4f98-9335-cbe6702bb6b3.png)

My prior comments were based on running on a Windows PC in my work environment. 

Then I decided to try Firefox v102.0.1  on my MBP and I get the CSP error I was getting at work:

![image](https://user-images.githubusercontent.com/11488937/180626716-55d11afe-6f17-472d-becb-a3555bdc1cfc.png)

Also on my MBP running macOS 12.5 - MS Edge Dev v105.0.1321.0 generates a CSP error, like Firefox does, but Google Chrome v103.0.5060.134 works like Safari:

![image](https://user-images.githubusercontent.com/11488937/180627026-50d4304e-a471-4c4e-a7d0-96832afb3070.png)

An aside - the grouped timing use case works in the Google Chrome console to illustrate the caching but throws an error in Safari:

![image](https://user-images.githubusercontent.com/11488937/180627363-a6e044b7-78f6-4d3c-a8b4-c90626e47734.png)


An interesting conundrum.

**Comment by hnkuanx** [comment]
CSP is usually enforced by the page you are on before opening up the dev console.

Try go to https://www.google.com before opening up the console to run adhoc script.

**Comment by enwinn** [comment]
Yes, thanks! That worked for both Firefox and Edge Dev (not shown):

![image](https://user-images.githubusercontent.com/11488937/180628326-cd358375-8b76-4c8d-b461-67a062855df1.png)

Interesting learning experience. Hope you don't mind me cluttering up your issues section.
